version: "3.7"

services:
  postgres:
    image: postgres:11.1-alpine
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "127.0.0.43:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker:
    image: dius/pact-broker:2.27.6-2
    # If you remove nginx, enable the following
    #ports:
    #  - "80:80"
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

  # Nginx is not necessary, but demonstrates how
  # one might use a reverse proxy in front of the broker,
  # and includes the use of a self-signed TLS certificate
  nginx:
    image: nginx:1.14.2-alpine
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "127.0.0.43:8443:443"
      - "127.0.0.43:80:80"
